# Generated by Django 5.2.4 on 2025-07-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='bot_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
